import { images } from './constants/index';

const data = {
  products: [
    {
      id: 0,
      title: 'CB125',
      slug: 'honda-cb125',
      category: 'motorcycle',
      price: 2900,
      img: images.honda1,
      amount: 1,
      brand: 'honda',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Honda CB125 Blue',
    },
    {
      id: 1,
      title: 'TVS tricycle',
      slug: 'tvs-tricycle',
      category: 'tricycle',
      price: 7000,
      img: images.tvstricycle,
      amount: 1,
      brand: 'TVS',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'TVS Tricycle',
    },
    {
      id: 2,
      title: 'hoajue lucky plus',
      slug: 'hoajue-lucky-plus',
      category: 'motorcycle',
      price: 4500,
      img: images.luckyplus,
      amount: 1,
      brand: 'hoajue',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'hoajue lucky plus',
    },
    {
      id: 3,
      title: 'haojue ud110',
      slug: 'haojue-ud110',
      category: 'motorcycle',
      price: 4000,
      img: images.ud110,
      amount: 1,
      brand: 'hoajue',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'hoajue ud cd110',
    },
    {
      id: 4,
      title: 'daylong tricycle',
      slug: 'daylog-tricycle',

      category: 'tricycle',
      price: 6500,
      img: images.daylongtri,
      amount: 1,
      brand: 'daylong',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'daylong tircycle',
    },
    {
      id: 5,
      title: 'haojue elegant',
      slug: 'haojue-elegant',
      category: 'motorcycle',
      price: 350000,
      img: images.elegent,
      amount: 1,
      brand: 'hoajue',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'hoajue elegent eg125',
    },
    {
      id: 6,
      title: 'haoujue lucky',
      slug: 'haojue-lucky',
      category: 'motorcycle',
      price: 500000,
      img: images.lucky,
      amount: 1,
      brand: 'hoajue',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'hoajue lucky cd110',
    },
    {
      id: 7,
      title: 'american power bike',
      slug: 'american-power-bike',
      category: 'motorcycle',
      price: 10000,
      img: images.power1,
      amount: 1,
      brand: 'power bike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'american power bike',
    },
    {
      id: 8,
      title: 'american power bike',
      slug: 'american-power-bike-2',
      category: 'motorcycle',
      price: 10000,
      img: images.power2,
      amount: 1,
      brand: 'power bike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'american power bike',
    },
    {
      id: 9,
      title: 'american power bike',
      slug: 'american-power-bike-2',
      category: 'motorcycle',
      price: 10000,
      img: images.power3,
      amount: 1,
      brand: 'power bike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'american power bike',
    },
    {
      id: 10,
      title: 'Bearing',
      slug: 'Bearing',
      category: 'spare-parts',
      price: 300,
      img: images.Bearing,
      amount: 1,
      brand: 'orange',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'bearing 6302 orange',
    },
    {
      id: 11,
      title: 'Crankshaft',
      slug: 'Crankshaft',
      category: 'spare-parts',
      price: 300,
      img: images.Crankshaft,
      amount: 1,
      brand: 'orange',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Crankshaft orange',
    },
    {
      id: 12,
      title: 'backDanger',
      slug: 'backDanger',
      category: 'spare-parts',
      price: 300,
      img: images.backDanger,
      amount: 1,
      brand: 'orange',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'backDanger boxer orange',
    },
    {
      id: 13,
      title: 'battery',
      slug: 'battery',
      category: 'spare-parts',
      price: 300,
      img: images.battery,
      amount: 1,
      brand: 'avata',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'avata battery',
    },
    {
      id: 14,
      title: 'Back shock',
      slug: 'Back shock',
      category: 'spare-parts',
      price: 500,
      img: images.bkshock,
      amount: 1,
      brand: 'orange',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'back shock absover',
    },
    {
      id: 15,
      title: 'chaincover',
      slug: 'chaincover',
      category: 'spare-parts',
      price: 300,
      img: images.chaincover,
      amount: 1,
      brand: 'orange',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'chaincover durable chaincover',
    },
    {
      id: 16,
      title: 'back Tire',
      slug: 'back Tire',
      category: 'spare-parts',
      price: 3000,
      img: images.tire,
      amount: 1,
      brand: 'CST',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'back Tire 300/18',
    },
    {
      id: 17,
      title: 'cilenser',
      slug: 'cilenser',
      category: 'spare-parts',
      price: 200,
      img: images.cilenser,
      amount: 1,
      brand: 'fire bird',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'cilenser fire bird cilenser',
    },
    {
      id: 18,
      title: 'frame',
      slug: 'frame',
      category: 'spare-parts',
      price: 300,
      img: images.frame,
      amount: 1,
      brand: 'orange',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'frame motorcycle body frame',
    },
  ],
};
export default data;
